name: flutter_jazzcash
description: A Flutter package for JazzCash payment integration supporting both mobile wallet and card payments.
version: 1.0.0
homepage: https://github.com/tjbaba/flutter_jazzcash
repository: https://github.com/tjbaba/flutter_jazzcash
issue_tracker: https://github.com/tjbaba/flutter_jazzcash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.3
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - payment
  - jazzcash
  - pakistan
  - mobile-wallet
  - card-payment